---
pid: tmp/pids/thin.pid
address: 0.0.0.0
timeout: 30
wait: 30
port: 4030
log: log/thin.log
max_conns: 1024
require: []

max_persistent_conns: 512
servers: 2
daemonize: true
#chdir: /var/www/apps/current
